"""empty message

Revision ID: 0a0af1cb524d
Revises: fe178d640aea
Create Date: 2019-03-04 11:56:52.030045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0af1cb524d'
down_revision = 'fe178d640aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'type')
    # ### end Alembic commands ###
