"""empty message

Revision ID: 199f23bc49d1
Revises: 0f6b00e45ec1
Create Date: 2019-03-14 11:22:12.385832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199f23bc49d1'
down_revision = '0f6b00e45ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('fixed_link', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'fixed_link')
    # ### end Alembic commands ###
