"""empty message

Revision ID: 24fe8452559a
Revises: 712e75803c32
Create Date: 2019-01-26 12:27:04.988036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24fe8452559a'
down_revision = '712e75803c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('reply_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['reply_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'reply_id')
    # ### end Alembic commands ###
