"""empty message

Revision ID: 3fb923d9931a
Revises: b698e8469854
Create Date: 2019-03-04 14:20:26.752076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb923d9931a'
down_revision = 'b698e8469854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'notifications', 'users', ['receiver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    # ### end Alembic commands ###
