"""empty message

Revision ID: 4043cc4402bf
Revises: 7e54eaab1da8
Create Date: 2019-01-27 23:03:27.891341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4043cc4402bf'
down_revision = '7e54eaab1da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_visit', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_visit')
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
