"""empty message

Revision ID: 5af2a2684630
Revises: 199f23bc49d1
Create Date: 2019-03-14 11:30:26.312754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af2a2684630'
down_revision = '199f23bc49d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('icon', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'icon')
    # ### end Alembic commands ###
