"""empty message

Revision ID: b698e8469854
Revises: 38b6e86c37f3
Create Date: 2019-03-04 13:06:42.519080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b698e8469854'
down_revision = '38b6e86c37f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('receiver_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'receiver_id')
    # ### end Alembic commands ###
