"""empty message

Revision ID: e60d5def54bd
Revises: 58f95e983e10
Create Date: 2019-03-03 20:17:42.352646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e60d5def54bd'
down_revision = '58f95e983e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.drop_index('ix_private_messages_timestamp', table_name='private_messages')
    op.drop_table('private_messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_messages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('recipient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('content', mysql.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name='private_messages_ibfk_1'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='private_messages_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_private_messages_timestamp', 'private_messages', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
